# Generated by Django 5.1.7 on 2025-04-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACME', '0003_faultcase_assigned_technicians'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warning',
            new_name='MachineWarning',
        ),
    ]
